apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-demo
  labels:
    app: python-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app-demo
  template:
    metadata:
      labels:
        app: python-app-demo
    spec:
      containers:
      - name: python-app-demo
        image: mayanks95/python-app-demo:v1
        ports:
        - containerPort: 5000
